maintainer       "Dell, Inc."
maintainer_email "Paul_Webster@Dell.com"
license          "Apache 2.0 License, Copyright (c) 2011 Dell Inc. - http://www.apache.org/licenses/LICENSE-2.0"
description      "Common libraries and utilities that provides the basic Hadoop runtime environment (HDFS/Map Reduce). A set of components and interfaces which implements a distributed filesystem and provides general I/O access for the hadoop framework (serialization, Java RPC and persistent data storage)."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "1.0"
recipe           "clouderamanager::cm-client", "Installs the Cloudera Manager client packages."
recipe           "clouderamanager::cm-common", "Installs Cloudera Manager common components."
recipe           "clouderamanager::cm-server", "Installs the Cloudera Manager server packages."
recipe           "clouderamanager::configure-disks", "Configure disks for the hadoop cluster."
recipe           "clouderamanager::default", "Installs hadoop base libraries and configuration."
recipe           "clouderamanager::mysql", "Installs the My SQL server for Cloudera Manager meta data."
recipe           "clouderamanager::postgresql", "Installs the PostgreSQL server for Cloudera Manager meta data."
